package com.bigbrightpaints.erp.modules.factory.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record ProductionLogDetailDto(
    Long id,
    UUID publicId,
    String productionCode,
    Instant producedAt,
    String brandName,
    String productName,
    String skuCode,
    String batchColour,
    BigDecimal batchSize,
    String unitOfMeasure,
    BigDecimal mixedQuantity,
    String outputBatchCode,
    BigDecimal outputQuantity,
    BigDecimal totalPackedQuantity,
    BigDecimal wastageQuantity,
    String wastageReasonCode,
    String status,
    BigDecimal materialCostTotal,
    BigDecimal laborCostTotal,
    BigDecimal overheadCostTotal,
    BigDecimal unitCost,
    Long salesOrderId,
    String salesOrderNumber,
    String notes,
    String createdBy,
    List<ProductionLogMaterialDto> materials,
    List<ProductionLogPackingRecordDto> packingRecords,
    String productFamilyName,
    List<AllowedSellableSizeDto> allowedSellableSizes) {
  public ProductionLogDetailDto(
      Long id,
      UUID publicId,
      String productionCode,
      Instant producedAt,
      String brandName,
      String productName,
      String skuCode,
      String batchColour,
      BigDecimal batchSize,
      String unitOfMeasure,
      BigDecimal mixedQuantity,
      String outputBatchCode,
      BigDecimal outputQuantity,
      BigDecimal totalPackedQuantity,
      BigDecimal wastageQuantity,
      String wastageReasonCode,
      String status,
      BigDecimal materialCostTotal,
      BigDecimal laborCostTotal,
      BigDecimal overheadCostTotal,
      BigDecimal unitCost,
      Long salesOrderId,
      String salesOrderNumber,
      String notes,
      String createdBy,
      List<ProductionLogMaterialDto> materials,
      List<ProductionLogPackingRecordDto> packingRecords) {
    this(
        id,
        publicId,
        productionCode,
        producedAt,
        brandName,
        productName,
        skuCode,
        batchColour,
        batchSize,
        unitOfMeasure,
        mixedQuantity,
        outputBatchCode,
        outputQuantity,
        totalPackedQuantity,
        wastageQuantity,
        wastageReasonCode,
        status,
        materialCostTotal,
        laborCostTotal,
        overheadCostTotal,
        unitCost,
        salesOrderId,
        salesOrderNumber,
        notes,
        createdBy,
        materials,
        packingRecords,
        null,
        List.of());
  }
}
