/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * DashboardControllerApi - axios parameter creator
 */
export const DashboardControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDashboard: async (xCompanyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('adminDashboard', 'xCompanyId', xCompanyId)
            const localVarPath = `/api/v1/orchestrator/dashboard/admin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        factoryDashboard: async (xCompanyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('factoryDashboard', 'xCompanyId', xCompanyId)
            const localVarPath = `/api/v1/orchestrator/dashboard/factory`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financeDashboard: async (xCompanyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('financeDashboard', 'xCompanyId', xCompanyId)
            const localVarPath = `/api/v1/orchestrator/dashboard/finance`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardControllerApi - functional programming interface
 */
export const DashboardControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminDashboard(xCompanyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminDashboard(xCompanyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardControllerApi.adminDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async factoryDashboard(xCompanyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.factoryDashboard(xCompanyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardControllerApi.factoryDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financeDashboard(xCompanyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financeDashboard(xCompanyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardControllerApi.financeDashboard']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DashboardControllerApi - factory interface
 */
export const DashboardControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DashboardControllerApiAdminDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminDashboard(requestParameters: DashboardControllerApiAdminDashboardRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.adminDashboard(requestParameters.xCompanyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DashboardControllerApiFactoryDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        factoryDashboard(requestParameters: DashboardControllerApiFactoryDashboardRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.factoryDashboard(requestParameters.xCompanyId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DashboardControllerApiFinanceDashboardRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financeDashboard(requestParameters: DashboardControllerApiFinanceDashboardRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.financeDashboard(requestParameters.xCompanyId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for adminDashboard operation in DashboardControllerApi.
 */
export interface DashboardControllerApiAdminDashboardRequest {
    readonly xCompanyId: string
}

/**
 * Request parameters for factoryDashboard operation in DashboardControllerApi.
 */
export interface DashboardControllerApiFactoryDashboardRequest {
    readonly xCompanyId: string
}

/**
 * Request parameters for financeDashboard operation in DashboardControllerApi.
 */
export interface DashboardControllerApiFinanceDashboardRequest {
    readonly xCompanyId: string
}

/**
 * DashboardControllerApi - object-oriented interface
 */
export class DashboardControllerApi extends BaseAPI {
    /**
     * 
     * @param {DashboardControllerApiAdminDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adminDashboard(requestParameters: DashboardControllerApiAdminDashboardRequest, options?: RawAxiosRequestConfig) {
        return DashboardControllerApiFp(this.configuration).adminDashboard(requestParameters.xCompanyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DashboardControllerApiFactoryDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public factoryDashboard(requestParameters: DashboardControllerApiFactoryDashboardRequest, options?: RawAxiosRequestConfig) {
        return DashboardControllerApiFp(this.configuration).factoryDashboard(requestParameters.xCompanyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DashboardControllerApiFinanceDashboardRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financeDashboard(requestParameters: DashboardControllerApiFinanceDashboardRequest, options?: RawAxiosRequestConfig) {
        return DashboardControllerApiFp(this.configuration).financeDashboard(requestParameters.xCompanyId, options).then((request) => request(this.axios, this.basePath));
    }
}

