/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseDealerResponse } from '../models';
// @ts-ignore
import type { ApiResponseListDealerLookupResponse } from '../models';
// @ts-ignore
import type { ApiResponseListDealerResponse } from '../models';
// @ts-ignore
import type { ApiResponseMapStringObject } from '../models';
// @ts-ignore
import type { CreateDealerRequest } from '../models';
/**
 * DealerControllerApi - axios parameter creator
 */
export const DealerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateDealerRequest} createDealerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDealer: async (createDealerRequest: CreateDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createDealerRequest' is not null or undefined
            assertParamExists('createDealer', 'createDealerRequest', createDealerRequest)
            const localVarPath = `/api/v1/dealers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} dealerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dealerLedger: async (dealerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dealerId' is not null or undefined
            assertParamExists('dealerLedger', 'dealerId', dealerId)
            const localVarPath = `/api/v1/dealers/{dealerId}/ledger`
                .replace(`{${"dealerId"}}`, encodeURIComponent(String(dealerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} dealerId 
         * @param {number} [overdueDays] 
         * @param {number} [minAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        holdIfOverdue: async (dealerId: number, overdueDays?: number, minAmount?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dealerId' is not null or undefined
            assertParamExists('holdIfOverdue', 'dealerId', dealerId)
            const localVarPath = `/api/v1/dealers/{dealerId}/dunning/hold`
                .replace(`{${"dealerId"}}`, encodeURIComponent(String(dealerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (overdueDays !== undefined) {
                localVarQueryParameter['overdueDays'] = overdueDays;
            }

            if (minAmount !== undefined) {
                localVarQueryParameter['minAmount'] = minAmount;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDealers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dealers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDealers: async (query?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dealers/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DealerControllerApi - functional programming interface
 */
export const DealerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DealerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateDealerRequest} createDealerRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDealer(createDealerRequest: CreateDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDealerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDealer(createDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealerControllerApi.createDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} dealerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dealerLedger(dealerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMapStringObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dealerLedger(dealerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealerControllerApi.dealerLedger']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} dealerId 
         * @param {number} [overdueDays] 
         * @param {number} [minAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async holdIfOverdue(dealerId: number, overdueDays?: number, minAmount?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMapStringObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.holdIfOverdue(dealerId, overdueDays, minAmount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealerControllerApi.holdIfOverdue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDealers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListDealerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDealers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealerControllerApi.listDealers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchDealers(query?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListDealerLookupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchDealers(query, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealerControllerApi.searchDealers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DealerControllerApi - factory interface
 */
export const DealerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DealerControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {DealerControllerApiCreateDealerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDealer(requestParameters: DealerControllerApiCreateDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDealerResponse> {
            return localVarFp.createDealer(requestParameters.createDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DealerControllerApiDealerLedgerRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dealerLedger(requestParameters: DealerControllerApiDealerLedgerRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMapStringObject> {
            return localVarFp.dealerLedger(requestParameters.dealerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DealerControllerApiHoldIfOverdueRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        holdIfOverdue(requestParameters: DealerControllerApiHoldIfOverdueRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMapStringObject> {
            return localVarFp.holdIfOverdue(requestParameters.dealerId, requestParameters.overdueDays, requestParameters.minAmount, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDealers(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListDealerResponse> {
            return localVarFp.listDealers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DealerControllerApiSearchDealersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDealers(requestParameters: DealerControllerApiSearchDealersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListDealerLookupResponse> {
            return localVarFp.searchDealers(requestParameters.query, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createDealer operation in DealerControllerApi.
 */
export interface DealerControllerApiCreateDealerRequest {
    readonly createDealerRequest: CreateDealerRequest
}

/**
 * Request parameters for dealerLedger operation in DealerControllerApi.
 */
export interface DealerControllerApiDealerLedgerRequest {
    readonly dealerId: number
}

/**
 * Request parameters for holdIfOverdue operation in DealerControllerApi.
 */
export interface DealerControllerApiHoldIfOverdueRequest {
    readonly dealerId: number

    readonly overdueDays?: number

    readonly minAmount?: number
}

/**
 * Request parameters for searchDealers operation in DealerControllerApi.
 */
export interface DealerControllerApiSearchDealersRequest {
    readonly query?: string
}

/**
 * DealerControllerApi - object-oriented interface
 */
export class DealerControllerApi extends BaseAPI {
    /**
     * 
     * @param {DealerControllerApiCreateDealerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDealer(requestParameters: DealerControllerApiCreateDealerRequest, options?: RawAxiosRequestConfig) {
        return DealerControllerApiFp(this.configuration).createDealer(requestParameters.createDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DealerControllerApiDealerLedgerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dealerLedger(requestParameters: DealerControllerApiDealerLedgerRequest, options?: RawAxiosRequestConfig) {
        return DealerControllerApiFp(this.configuration).dealerLedger(requestParameters.dealerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DealerControllerApiHoldIfOverdueRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public holdIfOverdue(requestParameters: DealerControllerApiHoldIfOverdueRequest, options?: RawAxiosRequestConfig) {
        return DealerControllerApiFp(this.configuration).holdIfOverdue(requestParameters.dealerId, requestParameters.overdueDays, requestParameters.minAmount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDealers(options?: RawAxiosRequestConfig) {
        return DealerControllerApiFp(this.configuration).listDealers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {DealerControllerApiSearchDealersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchDealers(requestParameters: DealerControllerApiSearchDealersRequest = {}, options?: RawAxiosRequestConfig) {
        return DealerControllerApiFp(this.configuration).searchDealers(requestParameters.query, options).then((request) => request(this.axios, this.basePath));
    }
}

