/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseCostAllocationResponse } from '../models';
// @ts-ignore
import type { ApiResponseFactoryDashboardDto } from '../models';
// @ts-ignore
import type { ApiResponseFactoryTaskDto } from '../models';
// @ts-ignore
import type { ApiResponseListFactoryTaskDto } from '../models';
// @ts-ignore
import type { ApiResponseListProductionBatchDto } from '../models';
// @ts-ignore
import type { ApiResponseListProductionPlanDto } from '../models';
// @ts-ignore
import type { ApiResponseProductionBatchDto } from '../models';
// @ts-ignore
import type { ApiResponseProductionPlanDto } from '../models';
// @ts-ignore
import type { CostAllocationRequest } from '../models';
// @ts-ignore
import type { FactoryTaskRequest } from '../models';
// @ts-ignore
import type { ProductionBatchRequest } from '../models';
// @ts-ignore
import type { ProductionPlanRequest } from '../models';
// @ts-ignore
import type { StatusRequest } from '../models';
/**
 * FactoryControllerApi - axios parameter creator
 */
export const FactoryControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CostAllocationRequest} costAllocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allocateCosts: async (costAllocationRequest: CostAllocationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'costAllocationRequest' is not null or undefined
            assertParamExists('allocateCosts', 'costAllocationRequest', costAllocationRequest)
            const localVarPath = `/api/v1/factory/cost-allocation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(costAllocationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batches1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/factory/production-batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProductionPlanRequest} productionPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan: async (productionPlanRequest: ProductionPlanRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productionPlanRequest' is not null or undefined
            assertParamExists('createPlan', 'productionPlanRequest', productionPlanRequest)
            const localVarPath = `/api/v1/factory/production-plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productionPlanRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {FactoryTaskRequest} factoryTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTask: async (factoryTaskRequest: FactoryTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'factoryTaskRequest' is not null or undefined
            assertParamExists('createTask', 'factoryTaskRequest', factoryTaskRequest)
            const localVarPath = `/api/v1/factory/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(factoryTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboard1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/factory/dashboard`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePlan: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePlan', 'id', id)
            const localVarPath = `/api/v1/factory/production-plans/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ProductionBatchRequest} productionBatchRequest 
         * @param {number} [planId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logBatch: async (productionBatchRequest: ProductionBatchRequest, planId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productionBatchRequest' is not null or undefined
            assertParamExists('logBatch', 'productionBatchRequest', productionBatchRequest)
            const localVarPath = `/api/v1/factory/production-batches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (planId !== undefined) {
                localVarQueryParameter['planId'] = planId;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productionBatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        plans: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/factory/production-plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/factory/tasks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {ProductionPlanRequest} productionPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlan: async (id: number, productionPlanRequest: ProductionPlanRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePlan', 'id', id)
            // verify required parameter 'productionPlanRequest' is not null or undefined
            assertParamExists('updatePlan', 'productionPlanRequest', productionPlanRequest)
            const localVarPath = `/api/v1/factory/production-plans/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productionPlanRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlanStatus: async (id: number, statusRequest: StatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePlanStatus', 'id', id)
            // verify required parameter 'statusRequest' is not null or undefined
            assertParamExists('updatePlanStatus', 'statusRequest', statusRequest)
            const localVarPath = `/api/v1/factory/production-plans/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(statusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {FactoryTaskRequest} factoryTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTask: async (id: number, factoryTaskRequest: FactoryTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTask', 'id', id)
            // verify required parameter 'factoryTaskRequest' is not null or undefined
            assertParamExists('updateTask', 'factoryTaskRequest', factoryTaskRequest)
            const localVarPath = `/api/v1/factory/tasks/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(factoryTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FactoryControllerApi - functional programming interface
 */
export const FactoryControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FactoryControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CostAllocationRequest} costAllocationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async allocateCosts(costAllocationRequest: CostAllocationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCostAllocationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.allocateCosts(costAllocationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.allocateCosts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batches1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductionBatchDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batches1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.batches1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProductionPlanRequest} productionPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPlan(productionPlanRequest: ProductionPlanRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProductionPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPlan(productionPlanRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.createPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {FactoryTaskRequest} factoryTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTask(factoryTaskRequest: FactoryTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseFactoryTaskDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTask(factoryTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.createTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dashboard1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseFactoryDashboardDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dashboard1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.dashboard1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePlan(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePlan(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.deletePlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ProductionBatchRequest} productionBatchRequest 
         * @param {number} [planId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logBatch(productionBatchRequest: ProductionBatchRequest, planId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProductionBatchDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logBatch(productionBatchRequest, planId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.logBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async plans(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductionPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.plans(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.plans']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tasks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListFactoryTaskDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tasks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.tasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {ProductionPlanRequest} productionPlanRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePlan(id: number, productionPlanRequest: ProductionPlanRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProductionPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePlan(id, productionPlanRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.updatePlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePlanStatus(id: number, statusRequest: StatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseProductionPlanDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePlanStatus(id, statusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.updatePlanStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {FactoryTaskRequest} factoryTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTask(id: number, factoryTaskRequest: FactoryTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseFactoryTaskDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTask(id, factoryTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FactoryControllerApi.updateTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FactoryControllerApi - factory interface
 */
export const FactoryControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FactoryControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {FactoryControllerApiAllocateCostsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        allocateCosts(requestParameters: FactoryControllerApiAllocateCostsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCostAllocationResponse> {
            return localVarFp.allocateCosts(requestParameters.costAllocationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batches1(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListProductionBatchDto> {
            return localVarFp.batches1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiCreatePlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan(requestParameters: FactoryControllerApiCreatePlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProductionPlanDto> {
            return localVarFp.createPlan(requestParameters.productionPlanRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiCreateTaskRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTask(requestParameters: FactoryControllerApiCreateTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFactoryTaskDto> {
            return localVarFp.createTask(requestParameters.factoryTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dashboard1(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFactoryDashboardDto> {
            return localVarFp.dashboard1(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiDeletePlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePlan(requestParameters: FactoryControllerApiDeletePlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePlan(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiLogBatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logBatch(requestParameters: FactoryControllerApiLogBatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProductionBatchDto> {
            return localVarFp.logBatch(requestParameters.productionBatchRequest, requestParameters.planId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        plans(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListProductionPlanDto> {
            return localVarFp.plans(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tasks(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListFactoryTaskDto> {
            return localVarFp.tasks(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiUpdatePlanRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlan(requestParameters: FactoryControllerApiUpdatePlanRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProductionPlanDto> {
            return localVarFp.updatePlan(requestParameters.id, requestParameters.productionPlanRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiUpdatePlanStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePlanStatus(requestParameters: FactoryControllerApiUpdatePlanStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseProductionPlanDto> {
            return localVarFp.updatePlanStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {FactoryControllerApiUpdateTaskRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTask(requestParameters: FactoryControllerApiUpdateTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFactoryTaskDto> {
            return localVarFp.updateTask(requestParameters.id, requestParameters.factoryTaskRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for allocateCosts operation in FactoryControllerApi.
 */
export interface FactoryControllerApiAllocateCostsRequest {
    readonly costAllocationRequest: CostAllocationRequest
}

/**
 * Request parameters for createPlan operation in FactoryControllerApi.
 */
export interface FactoryControllerApiCreatePlanRequest {
    readonly productionPlanRequest: ProductionPlanRequest
}

/**
 * Request parameters for createTask operation in FactoryControllerApi.
 */
export interface FactoryControllerApiCreateTaskRequest {
    readonly factoryTaskRequest: FactoryTaskRequest
}

/**
 * Request parameters for deletePlan operation in FactoryControllerApi.
 */
export interface FactoryControllerApiDeletePlanRequest {
    readonly id: number
}

/**
 * Request parameters for logBatch operation in FactoryControllerApi.
 */
export interface FactoryControllerApiLogBatchRequest {
    readonly productionBatchRequest: ProductionBatchRequest

    readonly planId?: number
}

/**
 * Request parameters for updatePlan operation in FactoryControllerApi.
 */
export interface FactoryControllerApiUpdatePlanRequest {
    readonly id: number

    readonly productionPlanRequest: ProductionPlanRequest
}

/**
 * Request parameters for updatePlanStatus operation in FactoryControllerApi.
 */
export interface FactoryControllerApiUpdatePlanStatusRequest {
    readonly id: number

    readonly statusRequest: StatusRequest
}

/**
 * Request parameters for updateTask operation in FactoryControllerApi.
 */
export interface FactoryControllerApiUpdateTaskRequest {
    readonly id: number

    readonly factoryTaskRequest: FactoryTaskRequest
}

/**
 * FactoryControllerApi - object-oriented interface
 */
export class FactoryControllerApi extends BaseAPI {
    /**
     * 
     * @param {FactoryControllerApiAllocateCostsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public allocateCosts(requestParameters: FactoryControllerApiAllocateCostsRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).allocateCosts(requestParameters.costAllocationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batches1(options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).batches1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiCreatePlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPlan(requestParameters: FactoryControllerApiCreatePlanRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).createPlan(requestParameters.productionPlanRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiCreateTaskRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTask(requestParameters: FactoryControllerApiCreateTaskRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).createTask(requestParameters.factoryTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dashboard1(options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).dashboard1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiDeletePlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePlan(requestParameters: FactoryControllerApiDeletePlanRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).deletePlan(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiLogBatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public logBatch(requestParameters: FactoryControllerApiLogBatchRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).logBatch(requestParameters.productionBatchRequest, requestParameters.planId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public plans(options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).plans(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public tasks(options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).tasks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiUpdatePlanRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePlan(requestParameters: FactoryControllerApiUpdatePlanRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).updatePlan(requestParameters.id, requestParameters.productionPlanRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiUpdatePlanStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePlanStatus(requestParameters: FactoryControllerApiUpdatePlanStatusRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).updatePlanStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {FactoryControllerApiUpdateTaskRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTask(requestParameters: FactoryControllerApiUpdateTaskRequest, options?: RawAxiosRequestConfig) {
        return FactoryControllerApiFp(this.configuration).updateTask(requestParameters.id, requestParameters.factoryTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

