/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseEmployeeDto } from '../models';
// @ts-ignore
import type { ApiResponseLeaveRequestDto } from '../models';
// @ts-ignore
import type { ApiResponseListEmployeeDto } from '../models';
// @ts-ignore
import type { ApiResponseListLeaveRequestDto } from '../models';
// @ts-ignore
import type { ApiResponseListPayrollRunDto } from '../models';
// @ts-ignore
import type { ApiResponsePayrollRunDto } from '../models';
// @ts-ignore
import type { EmployeeRequest } from '../models';
// @ts-ignore
import type { LeaveRequestRequest } from '../models';
// @ts-ignore
import type { PayrollRunRequest } from '../models';
// @ts-ignore
import type { StatusRequest } from '../models';
/**
 * HrControllerApi - axios parameter creator
 */
export const HrControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EmployeeRequest} employeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEmployee: async (employeeRequest: EmployeeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'employeeRequest' is not null or undefined
            assertParamExists('createEmployee', 'employeeRequest', employeeRequest)
            const localVarPath = `/api/v1/hr/employees`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(employeeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LeaveRequestRequest} leaveRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLeaveRequest: async (leaveRequestRequest: LeaveRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leaveRequestRequest' is not null or undefined
            assertParamExists('createLeaveRequest', 'leaveRequestRequest', leaveRequestRequest)
            const localVarPath = `/api/v1/hr/leave-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(leaveRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PayrollRunRequest} payrollRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayrollRun: async (payrollRunRequest: PayrollRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'payrollRunRequest' is not null or undefined
            assertParamExists('createPayrollRun', 'payrollRunRequest', payrollRunRequest)
            const localVarPath = `/api/v1/hr/payroll-runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(payrollRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEmployee: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteEmployee', 'id', id)
            const localVarPath = `/api/v1/hr/employees/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        employees: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/hr/employees`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaveRequests: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/hr/leave-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        payrollRuns: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/hr/payroll-runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {EmployeeRequest} employeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEmployee: async (id: number, employeeRequest: EmployeeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateEmployee', 'id', id)
            // verify required parameter 'employeeRequest' is not null or undefined
            assertParamExists('updateEmployee', 'employeeRequest', employeeRequest)
            const localVarPath = `/api/v1/hr/employees/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(employeeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLeaveStatus: async (id: number, statusRequest: StatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateLeaveStatus', 'id', id)
            // verify required parameter 'statusRequest' is not null or undefined
            assertParamExists('updateLeaveStatus', 'statusRequest', statusRequest)
            const localVarPath = `/api/v1/hr/leave-requests/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(statusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HrControllerApi - functional programming interface
 */
export const HrControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HrControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {EmployeeRequest} employeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createEmployee(employeeRequest: EmployeeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseEmployeeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createEmployee(employeeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.createEmployee']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {LeaveRequestRequest} leaveRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLeaveRequest(leaveRequestRequest: LeaveRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLeaveRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLeaveRequest(leaveRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.createLeaveRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PayrollRunRequest} payrollRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPayrollRun(payrollRunRequest: PayrollRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePayrollRunDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPayrollRun(payrollRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.createPayrollRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteEmployee(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteEmployee(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.deleteEmployee']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async employees(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListEmployeeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.employees(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.employees']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async leaveRequests(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListLeaveRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.leaveRequests(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.leaveRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async payrollRuns(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListPayrollRunDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.payrollRuns(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.payrollRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {EmployeeRequest} employeeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateEmployee(id: number, employeeRequest: EmployeeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseEmployeeDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateEmployee(id, employeeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.updateEmployee']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLeaveStatus(id: number, statusRequest: StatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLeaveRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLeaveStatus(id, statusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HrControllerApi.updateLeaveStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HrControllerApi - factory interface
 */
export const HrControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HrControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {HrControllerApiCreateEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createEmployee(requestParameters: HrControllerApiCreateEmployeeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseEmployeeDto> {
            return localVarFp.createEmployee(requestParameters.employeeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HrControllerApiCreateLeaveRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLeaveRequest(requestParameters: HrControllerApiCreateLeaveRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLeaveRequestDto> {
            return localVarFp.createLeaveRequest(requestParameters.leaveRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HrControllerApiCreatePayrollRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPayrollRun(requestParameters: HrControllerApiCreatePayrollRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePayrollRunDto> {
            return localVarFp.createPayrollRun(requestParameters.payrollRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HrControllerApiDeleteEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteEmployee(requestParameters: HrControllerApiDeleteEmployeeRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteEmployee(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        employees(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListEmployeeDto> {
            return localVarFp.employees(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        leaveRequests(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListLeaveRequestDto> {
            return localVarFp.leaveRequests(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        payrollRuns(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListPayrollRunDto> {
            return localVarFp.payrollRuns(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HrControllerApiUpdateEmployeeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateEmployee(requestParameters: HrControllerApiUpdateEmployeeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseEmployeeDto> {
            return localVarFp.updateEmployee(requestParameters.id, requestParameters.employeeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {HrControllerApiUpdateLeaveStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLeaveStatus(requestParameters: HrControllerApiUpdateLeaveStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLeaveRequestDto> {
            return localVarFp.updateLeaveStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createEmployee operation in HrControllerApi.
 */
export interface HrControllerApiCreateEmployeeRequest {
    readonly employeeRequest: EmployeeRequest
}

/**
 * Request parameters for createLeaveRequest operation in HrControllerApi.
 */
export interface HrControllerApiCreateLeaveRequestRequest {
    readonly leaveRequestRequest: LeaveRequestRequest
}

/**
 * Request parameters for createPayrollRun operation in HrControllerApi.
 */
export interface HrControllerApiCreatePayrollRunRequest {
    readonly payrollRunRequest: PayrollRunRequest
}

/**
 * Request parameters for deleteEmployee operation in HrControllerApi.
 */
export interface HrControllerApiDeleteEmployeeRequest {
    readonly id: number
}

/**
 * Request parameters for updateEmployee operation in HrControllerApi.
 */
export interface HrControllerApiUpdateEmployeeRequest {
    readonly id: number

    readonly employeeRequest: EmployeeRequest
}

/**
 * Request parameters for updateLeaveStatus operation in HrControllerApi.
 */
export interface HrControllerApiUpdateLeaveStatusRequest {
    readonly id: number

    readonly statusRequest: StatusRequest
}

/**
 * HrControllerApi - object-oriented interface
 */
export class HrControllerApi extends BaseAPI {
    /**
     * 
     * @param {HrControllerApiCreateEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createEmployee(requestParameters: HrControllerApiCreateEmployeeRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).createEmployee(requestParameters.employeeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HrControllerApiCreateLeaveRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createLeaveRequest(requestParameters: HrControllerApiCreateLeaveRequestRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).createLeaveRequest(requestParameters.leaveRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HrControllerApiCreatePayrollRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPayrollRun(requestParameters: HrControllerApiCreatePayrollRunRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).createPayrollRun(requestParameters.payrollRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HrControllerApiDeleteEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteEmployee(requestParameters: HrControllerApiDeleteEmployeeRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).deleteEmployee(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public employees(options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).employees(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public leaveRequests(options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).leaveRequests(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public payrollRuns(options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).payrollRuns(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HrControllerApiUpdateEmployeeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateEmployee(requestParameters: HrControllerApiUpdateEmployeeRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).updateEmployee(requestParameters.id, requestParameters.employeeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {HrControllerApiUpdateLeaveStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateLeaveStatus(requestParameters: HrControllerApiUpdateLeaveStatusRequest, options?: RawAxiosRequestConfig) {
        return HrControllerApiFp(this.configuration).updateLeaveStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

