/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseInventoryAdjustmentDto } from '../models';
// @ts-ignore
import type { ApiResponseListInventoryAdjustmentDto } from '../models';
// @ts-ignore
import type { InventoryAdjustmentRequest } from '../models';
/**
 * InventoryAdjustmentControllerApi - axios parameter creator
 */
export const InventoryAdjustmentControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {InventoryAdjustmentRequest} inventoryAdjustmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdjustment: async (inventoryAdjustmentRequest: InventoryAdjustmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inventoryAdjustmentRequest' is not null or undefined
            assertParamExists('createAdjustment', 'inventoryAdjustmentRequest', inventoryAdjustmentRequest)
            const localVarPath = `/api/v1/inventory/adjustments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(inventoryAdjustmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAdjustments: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/inventory/adjustments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InventoryAdjustmentControllerApi - functional programming interface
 */
export const InventoryAdjustmentControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InventoryAdjustmentControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {InventoryAdjustmentRequest} inventoryAdjustmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAdjustment(inventoryAdjustmentRequest: InventoryAdjustmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseInventoryAdjustmentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAdjustment(inventoryAdjustmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryAdjustmentControllerApi.createAdjustment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAdjustments(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListInventoryAdjustmentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAdjustments(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InventoryAdjustmentControllerApi.listAdjustments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InventoryAdjustmentControllerApi - factory interface
 */
export const InventoryAdjustmentControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InventoryAdjustmentControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {InventoryAdjustmentControllerApiCreateAdjustmentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdjustment(requestParameters: InventoryAdjustmentControllerApiCreateAdjustmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseInventoryAdjustmentDto> {
            return localVarFp.createAdjustment(requestParameters.inventoryAdjustmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAdjustments(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListInventoryAdjustmentDto> {
            return localVarFp.listAdjustments(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createAdjustment operation in InventoryAdjustmentControllerApi.
 */
export interface InventoryAdjustmentControllerApiCreateAdjustmentRequest {
    readonly inventoryAdjustmentRequest: InventoryAdjustmentRequest
}

/**
 * InventoryAdjustmentControllerApi - object-oriented interface
 */
export class InventoryAdjustmentControllerApi extends BaseAPI {
    /**
     * 
     * @param {InventoryAdjustmentControllerApiCreateAdjustmentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAdjustment(requestParameters: InventoryAdjustmentControllerApiCreateAdjustmentRequest, options?: RawAxiosRequestConfig) {
        return InventoryAdjustmentControllerApiFp(this.configuration).createAdjustment(requestParameters.inventoryAdjustmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAdjustments(options?: RawAxiosRequestConfig) {
        return InventoryAdjustmentControllerApiFp(this.configuration).listAdjustments(options).then((request) => request(this.axios, this.basePath));
    }
}

