/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApproveOrderRequest } from '../models';
// @ts-ignore
import type { DispatchRequest } from '../models';
// @ts-ignore
import type { OrderFulfillmentRequest } from '../models';
// @ts-ignore
import type { PayrollRunRequest } from '../models';
/**
 * OrchestratorControllerApi - axios parameter creator
 */
export const OrchestratorControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} orderId 
         * @param {string} xCompanyId 
         * @param {ApproveOrderRequest} approveOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveOrder: async (orderId: string, xCompanyId: string, approveOrderRequest: ApproveOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('approveOrder', 'orderId', orderId)
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('approveOrder', 'xCompanyId', xCompanyId)
            // verify required parameter 'approveOrderRequest' is not null or undefined
            assertParamExists('approveOrder', 'approveOrderRequest', approveOrderRequest)
            const localVarPath = `/api/v1/orchestrator/orders/{orderId}/approve`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(approveOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} batchId 
         * @param {string} xCompanyId 
         * @param {DispatchRequest} dispatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dispatch: async (batchId: string, xCompanyId: string, dispatchRequest: DispatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchId' is not null or undefined
            assertParamExists('dispatch', 'batchId', batchId)
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('dispatch', 'xCompanyId', xCompanyId)
            // verify required parameter 'dispatchRequest' is not null or undefined
            assertParamExists('dispatch', 'dispatchRequest', dispatchRequest)
            const localVarPath = `/api/v1/orchestrator/factory/dispatch/{batchId}`
                .replace(`{${"batchId"}}`, encodeURIComponent(String(batchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dispatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {{ [key: string]: object; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dispatchOrder: async (xCompanyId: string, requestBody: { [key: string]: object; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('dispatchOrder', 'xCompanyId', xCompanyId)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('dispatchOrder', 'requestBody', requestBody)
            const localVarPath = `/api/v1/orchestrator/dispatch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/orchestrator/health/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} orderId 
         * @param {string} xCompanyId 
         * @param {OrderFulfillmentRequest} orderFulfillmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fulfillOrder: async (orderId: string, xCompanyId: string, orderFulfillmentRequest: OrderFulfillmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('fulfillOrder', 'orderId', orderId)
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('fulfillOrder', 'xCompanyId', xCompanyId)
            // verify required parameter 'orderFulfillmentRequest' is not null or undefined
            assertParamExists('fulfillOrder', 'orderFulfillmentRequest', orderFulfillmentRequest)
            const localVarPath = `/api/v1/orchestrator/orders/{orderId}/fulfillment`
                .replace(`{${"orderId"}}`, encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(orderFulfillmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        integrationsHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/orchestrator/health/integrations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {PayrollRunRequest} payrollRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runPayroll: async (xCompanyId: string, payrollRunRequest: PayrollRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xCompanyId' is not null or undefined
            assertParamExists('runPayroll', 'xCompanyId', xCompanyId)
            // verify required parameter 'payrollRunRequest' is not null or undefined
            assertParamExists('runPayroll', 'payrollRunRequest', payrollRunRequest)
            const localVarPath = `/api/v1/orchestrator/payroll/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xCompanyId != null) {
                localVarHeaderParameter['X-Company-Id'] = String(xCompanyId);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(payrollRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} traceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trace: async (traceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'traceId' is not null or undefined
            assertParamExists('trace', 'traceId', traceId)
            const localVarPath = `/api/v1/orchestrator/traces/{traceId}`
                .replace(`{${"traceId"}}`, encodeURIComponent(String(traceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrchestratorControllerApi - functional programming interface
 */
export const OrchestratorControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrchestratorControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} orderId 
         * @param {string} xCompanyId 
         * @param {ApproveOrderRequest} approveOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveOrder(orderId: string, xCompanyId: string, approveOrderRequest: ApproveOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveOrder(orderId, xCompanyId, approveOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.approveOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} batchId 
         * @param {string} xCompanyId 
         * @param {DispatchRequest} dispatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dispatch(batchId: string, xCompanyId: string, dispatchRequest: DispatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dispatch(batchId, xCompanyId, dispatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.dispatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {{ [key: string]: object; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dispatchOrder(xCompanyId: string, requestBody: { [key: string]: object; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dispatchOrder(xCompanyId, requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.dispatchOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.eventHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} orderId 
         * @param {string} xCompanyId 
         * @param {OrderFulfillmentRequest} orderFulfillmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fulfillOrder(orderId: string, xCompanyId: string, orderFulfillmentRequest: OrderFulfillmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fulfillOrder(orderId, xCompanyId, orderFulfillmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.fulfillOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async integrationsHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.integrationsHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.integrationsHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} xCompanyId 
         * @param {PayrollRunRequest} payrollRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runPayroll(xCompanyId: string, payrollRunRequest: PayrollRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runPayroll(xCompanyId, payrollRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.runPayroll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} traceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async trace(traceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: object; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.trace(traceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrchestratorControllerApi.trace']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrchestratorControllerApi - factory interface
 */
export const OrchestratorControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrchestratorControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {OrchestratorControllerApiApproveOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveOrder(requestParameters: OrchestratorControllerApiApproveOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.approveOrder(requestParameters.orderId, requestParameters.xCompanyId, requestParameters.approveOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrchestratorControllerApiDispatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dispatch(requestParameters: OrchestratorControllerApiDispatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.dispatch(requestParameters.batchId, requestParameters.xCompanyId, requestParameters.dispatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrchestratorControllerApiDispatchOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dispatchOrder(requestParameters: OrchestratorControllerApiDispatchOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.dispatchOrder(requestParameters.xCompanyId, requestParameters.requestBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventHealth(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.eventHealth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrchestratorControllerApiFulfillOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fulfillOrder(requestParameters: OrchestratorControllerApiFulfillOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.fulfillOrder(requestParameters.orderId, requestParameters.xCompanyId, requestParameters.orderFulfillmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        integrationsHealth(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.integrationsHealth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrchestratorControllerApiRunPayrollRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runPayroll(requestParameters: OrchestratorControllerApiRunPayrollRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.runPayroll(requestParameters.xCompanyId, requestParameters.payrollRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OrchestratorControllerApiTraceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        trace(requestParameters: OrchestratorControllerApiTraceRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: object; }> {
            return localVarFp.trace(requestParameters.traceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for approveOrder operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiApproveOrderRequest {
    readonly orderId: string

    readonly xCompanyId: string

    readonly approveOrderRequest: ApproveOrderRequest
}

/**
 * Request parameters for dispatch operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiDispatchRequest {
    readonly batchId: string

    readonly xCompanyId: string

    readonly dispatchRequest: DispatchRequest
}

/**
 * Request parameters for dispatchOrder operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiDispatchOrderRequest {
    readonly xCompanyId: string

    readonly requestBody: { [key: string]: object; }
}

/**
 * Request parameters for fulfillOrder operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiFulfillOrderRequest {
    readonly orderId: string

    readonly xCompanyId: string

    readonly orderFulfillmentRequest: OrderFulfillmentRequest
}

/**
 * Request parameters for runPayroll operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiRunPayrollRequest {
    readonly xCompanyId: string

    readonly payrollRunRequest: PayrollRunRequest
}

/**
 * Request parameters for trace operation in OrchestratorControllerApi.
 */
export interface OrchestratorControllerApiTraceRequest {
    readonly traceId: string
}

/**
 * OrchestratorControllerApi - object-oriented interface
 */
export class OrchestratorControllerApi extends BaseAPI {
    /**
     * 
     * @param {OrchestratorControllerApiApproveOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public approveOrder(requestParameters: OrchestratorControllerApiApproveOrderRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).approveOrder(requestParameters.orderId, requestParameters.xCompanyId, requestParameters.approveOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrchestratorControllerApiDispatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dispatch(requestParameters: OrchestratorControllerApiDispatchRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).dispatch(requestParameters.batchId, requestParameters.xCompanyId, requestParameters.dispatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrchestratorControllerApiDispatchOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public dispatchOrder(requestParameters: OrchestratorControllerApiDispatchOrderRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).dispatchOrder(requestParameters.xCompanyId, requestParameters.requestBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public eventHealth(options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).eventHealth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrchestratorControllerApiFulfillOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fulfillOrder(requestParameters: OrchestratorControllerApiFulfillOrderRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).fulfillOrder(requestParameters.orderId, requestParameters.xCompanyId, requestParameters.orderFulfillmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public integrationsHealth(options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).integrationsHealth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrchestratorControllerApiRunPayrollRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runPayroll(requestParameters: OrchestratorControllerApiRunPayrollRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).runPayroll(requestParameters.xCompanyId, requestParameters.payrollRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {OrchestratorControllerApiTraceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public trace(requestParameters: OrchestratorControllerApiTraceRequest, options?: RawAxiosRequestConfig) {
        return OrchestratorControllerApiFp(this.configuration).trace(requestParameters.traceId, options).then((request) => request(this.axios, this.basePath));
    }
}

