/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListProductionBrandDto } from '../models';
// @ts-ignore
import type { ApiResponseListProductionProductDto } from '../models';
/**
 * ProductionCatalogControllerApi - axios parameter creator
 */
export const ProductionCatalogControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} brandId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBrandProducts: async (brandId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'brandId' is not null or undefined
            assertParamExists('listBrandProducts', 'brandId', brandId)
            const localVarPath = `/api/v1/production/brands/{brandId}/products`
                .replace(`{${"brandId"}}`, encodeURIComponent(String(brandId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBrands: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/production/brands`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductionCatalogControllerApi - functional programming interface
 */
export const ProductionCatalogControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductionCatalogControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} brandId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBrandProducts(brandId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductionProductDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBrandProducts(brandId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductionCatalogControllerApi.listBrandProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBrands(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListProductionBrandDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBrands(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductionCatalogControllerApi.listBrands']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProductionCatalogControllerApi - factory interface
 */
export const ProductionCatalogControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductionCatalogControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ProductionCatalogControllerApiListBrandProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBrandProducts(requestParameters: ProductionCatalogControllerApiListBrandProductsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListProductionProductDto> {
            return localVarFp.listBrandProducts(requestParameters.brandId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBrands(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListProductionBrandDto> {
            return localVarFp.listBrands(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listBrandProducts operation in ProductionCatalogControllerApi.
 */
export interface ProductionCatalogControllerApiListBrandProductsRequest {
    readonly brandId: number
}

/**
 * ProductionCatalogControllerApi - object-oriented interface
 */
export class ProductionCatalogControllerApi extends BaseAPI {
    /**
     * 
     * @param {ProductionCatalogControllerApiListBrandProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBrandProducts(requestParameters: ProductionCatalogControllerApiListBrandProductsRequest, options?: RawAxiosRequestConfig) {
        return ProductionCatalogControllerApiFp(this.configuration).listBrandProducts(requestParameters.brandId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBrands(options?: RawAxiosRequestConfig) {
        return ProductionCatalogControllerApiFp(this.configuration).listBrands(options).then((request) => request(this.axios, this.basePath));
    }
}

