/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListInventoryStockSnapshot } from '../models';
// @ts-ignore
import type { ApiResponseListRawMaterialBatchDto } from '../models';
// @ts-ignore
import type { ApiResponseListRawMaterialDto } from '../models';
// @ts-ignore
import type { ApiResponseRawMaterialBatchDto } from '../models';
// @ts-ignore
import type { ApiResponseRawMaterialDto } from '../models';
// @ts-ignore
import type { ApiResponseStockSummaryDto } from '../models';
// @ts-ignore
import type { RawMaterialBatchRequest } from '../models';
// @ts-ignore
import type { RawMaterialIntakeRequest } from '../models';
// @ts-ignore
import type { RawMaterialRequest } from '../models';
/**
 * RawMaterialControllerApi - axios parameter creator
 */
export const RawMaterialControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} rawMaterialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batches: async (rawMaterialId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rawMaterialId' is not null or undefined
            assertParamExists('batches', 'rawMaterialId', rawMaterialId)
            const localVarPath = `/api/v1/raw-material-batches/{rawMaterialId}`
                .replace(`{${"rawMaterialId"}}`, encodeURIComponent(String(rawMaterialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} rawMaterialId 
         * @param {RawMaterialBatchRequest} rawMaterialBatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatch: async (rawMaterialId: number, rawMaterialBatchRequest: RawMaterialBatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rawMaterialId' is not null or undefined
            assertParamExists('createBatch', 'rawMaterialId', rawMaterialId)
            // verify required parameter 'rawMaterialBatchRequest' is not null or undefined
            assertParamExists('createBatch', 'rawMaterialBatchRequest', rawMaterialBatchRequest)
            const localVarPath = `/api/v1/raw-material-batches/{rawMaterialId}`
                .replace(`{${"rawMaterialId"}}`, encodeURIComponent(String(rawMaterialId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rawMaterialBatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RawMaterialRequest} rawMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRawMaterial: async (rawMaterialRequest: RawMaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rawMaterialRequest' is not null or undefined
            assertParamExists('createRawMaterial', 'rawMaterialRequest', rawMaterialRequest)
            const localVarPath = `/api/v1/accounting/raw-materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rawMaterialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRawMaterial: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteRawMaterial', 'id', id)
            const localVarPath = `/api/v1/accounting/raw-materials/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RawMaterialIntakeRequest} rawMaterialIntakeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intake: async (rawMaterialIntakeRequest: RawMaterialIntakeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rawMaterialIntakeRequest' is not null or undefined
            assertParamExists('intake', 'rawMaterialIntakeRequest', rawMaterialIntakeRequest)
            const localVarPath = `/api/v1/raw-materials/intake`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rawMaterialIntakeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/raw-materials/stock/inventory`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRawMaterials: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/accounting/raw-materials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lowStock: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/raw-materials/stock/low-stock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stockSummary: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/raw-materials/stock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {RawMaterialRequest} rawMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRawMaterial: async (id: number, rawMaterialRequest: RawMaterialRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateRawMaterial', 'id', id)
            // verify required parameter 'rawMaterialRequest' is not null or undefined
            assertParamExists('updateRawMaterial', 'rawMaterialRequest', rawMaterialRequest)
            const localVarPath = `/api/v1/accounting/raw-materials/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rawMaterialRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RawMaterialControllerApi - functional programming interface
 */
export const RawMaterialControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RawMaterialControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} rawMaterialId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async batches(rawMaterialId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListRawMaterialBatchDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.batches(rawMaterialId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.batches']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} rawMaterialId 
         * @param {RawMaterialBatchRequest} rawMaterialBatchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBatch(rawMaterialId: number, rawMaterialBatchRequest: RawMaterialBatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialBatchDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBatch(rawMaterialId, rawMaterialBatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.createBatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RawMaterialRequest} rawMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRawMaterial(rawMaterialRequest: RawMaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRawMaterial(rawMaterialRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.createRawMaterial']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRawMaterial(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRawMaterial(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.deleteRawMaterial']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RawMaterialIntakeRequest} rawMaterialIntakeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async intake(rawMaterialIntakeRequest: RawMaterialIntakeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialBatchDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.intake(rawMaterialIntakeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.intake']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async inventory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListInventoryStockSnapshot>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.inventory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.inventory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listRawMaterials(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListRawMaterialDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listRawMaterials(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.listRawMaterials']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async lowStock(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListInventoryStockSnapshot>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.lowStock(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.lowStock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async stockSummary(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseStockSummaryDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.stockSummary(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.stockSummary']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {RawMaterialRequest} rawMaterialRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRawMaterial(id: number, rawMaterialRequest: RawMaterialRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRawMaterial(id, rawMaterialRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialControllerApi.updateRawMaterial']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RawMaterialControllerApi - factory interface
 */
export const RawMaterialControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RawMaterialControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {RawMaterialControllerApiBatchesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        batches(requestParameters: RawMaterialControllerApiBatchesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListRawMaterialBatchDto> {
            return localVarFp.batches(requestParameters.rawMaterialId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialControllerApiCreateBatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBatch(requestParameters: RawMaterialControllerApiCreateBatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialBatchDto> {
            return localVarFp.createBatch(requestParameters.rawMaterialId, requestParameters.rawMaterialBatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialControllerApiCreateRawMaterialRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRawMaterial(requestParameters: RawMaterialControllerApiCreateRawMaterialRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialDto> {
            return localVarFp.createRawMaterial(requestParameters.rawMaterialRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialControllerApiDeleteRawMaterialRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRawMaterial(requestParameters: RawMaterialControllerApiDeleteRawMaterialRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteRawMaterial(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialControllerApiIntakeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        intake(requestParameters: RawMaterialControllerApiIntakeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialBatchDto> {
            return localVarFp.intake(requestParameters.rawMaterialIntakeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        inventory(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListInventoryStockSnapshot> {
            return localVarFp.inventory(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listRawMaterials(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListRawMaterialDto> {
            return localVarFp.listRawMaterials(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        lowStock(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListInventoryStockSnapshot> {
            return localVarFp.lowStock(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        stockSummary(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseStockSummaryDto> {
            return localVarFp.stockSummary(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialControllerApiUpdateRawMaterialRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRawMaterial(requestParameters: RawMaterialControllerApiUpdateRawMaterialRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialDto> {
            return localVarFp.updateRawMaterial(requestParameters.id, requestParameters.rawMaterialRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for batches operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiBatchesRequest {
    readonly rawMaterialId: number
}

/**
 * Request parameters for createBatch operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiCreateBatchRequest {
    readonly rawMaterialId: number

    readonly rawMaterialBatchRequest: RawMaterialBatchRequest
}

/**
 * Request parameters for createRawMaterial operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiCreateRawMaterialRequest {
    readonly rawMaterialRequest: RawMaterialRequest
}

/**
 * Request parameters for deleteRawMaterial operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiDeleteRawMaterialRequest {
    readonly id: number
}

/**
 * Request parameters for intake operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiIntakeRequest {
    readonly rawMaterialIntakeRequest: RawMaterialIntakeRequest
}

/**
 * Request parameters for updateRawMaterial operation in RawMaterialControllerApi.
 */
export interface RawMaterialControllerApiUpdateRawMaterialRequest {
    readonly id: number

    readonly rawMaterialRequest: RawMaterialRequest
}

/**
 * RawMaterialControllerApi - object-oriented interface
 */
export class RawMaterialControllerApi extends BaseAPI {
    /**
     * 
     * @param {RawMaterialControllerApiBatchesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public batches(requestParameters: RawMaterialControllerApiBatchesRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).batches(requestParameters.rawMaterialId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialControllerApiCreateBatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createBatch(requestParameters: RawMaterialControllerApiCreateBatchRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).createBatch(requestParameters.rawMaterialId, requestParameters.rawMaterialBatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialControllerApiCreateRawMaterialRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createRawMaterial(requestParameters: RawMaterialControllerApiCreateRawMaterialRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).createRawMaterial(requestParameters.rawMaterialRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialControllerApiDeleteRawMaterialRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRawMaterial(requestParameters: RawMaterialControllerApiDeleteRawMaterialRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).deleteRawMaterial(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialControllerApiIntakeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public intake(requestParameters: RawMaterialControllerApiIntakeRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).intake(requestParameters.rawMaterialIntakeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public inventory(options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).inventory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listRawMaterials(options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).listRawMaterials(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public lowStock(options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).lowStock(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public stockSummary(options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).stockSummary(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialControllerApiUpdateRawMaterialRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRawMaterial(requestParameters: RawMaterialControllerApiUpdateRawMaterialRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialControllerApiFp(this.configuration).updateRawMaterial(requestParameters.id, requestParameters.rawMaterialRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

