/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseJournalEntryDto } from '../models';
// @ts-ignore
import type { ApiResponseListRawMaterialPurchaseResponse } from '../models';
// @ts-ignore
import type { ApiResponseRawMaterialPurchaseResponse } from '../models';
// @ts-ignore
import type { PurchaseReturnRequest } from '../models';
// @ts-ignore
import type { RawMaterialPurchaseRequest } from '../models';
/**
 * RawMaterialPurchaseControllerApi - axios parameter creator
 */
export const RawMaterialPurchaseControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RawMaterialPurchaseRequest} rawMaterialPurchaseRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPurchase: async (rawMaterialPurchaseRequest: RawMaterialPurchaseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rawMaterialPurchaseRequest' is not null or undefined
            assertParamExists('createPurchase', 'rawMaterialPurchaseRequest', rawMaterialPurchaseRequest)
            const localVarPath = `/api/v1/purchasing/raw-material-purchases`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rawMaterialPurchaseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPurchase: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPurchase', 'id', id)
            const localVarPath = `/api/v1/purchasing/raw-material-purchases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPurchases: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/purchasing/raw-material-purchases`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PurchaseReturnRequest} purchaseReturnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordPurchaseReturn: async (purchaseReturnRequest: PurchaseReturnRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'purchaseReturnRequest' is not null or undefined
            assertParamExists('recordPurchaseReturn', 'purchaseReturnRequest', purchaseReturnRequest)
            const localVarPath = `/api/v1/purchasing/raw-material-purchases/returns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(purchaseReturnRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RawMaterialPurchaseControllerApi - functional programming interface
 */
export const RawMaterialPurchaseControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RawMaterialPurchaseControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RawMaterialPurchaseRequest} rawMaterialPurchaseRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPurchase(rawMaterialPurchaseRequest: RawMaterialPurchaseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialPurchaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPurchase(rawMaterialPurchaseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialPurchaseControllerApi.createPurchase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPurchase(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseRawMaterialPurchaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPurchase(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialPurchaseControllerApi.getPurchase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPurchases(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListRawMaterialPurchaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPurchases(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialPurchaseControllerApi.listPurchases']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PurchaseReturnRequest} purchaseReturnRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordPurchaseReturn(purchaseReturnRequest: PurchaseReturnRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseJournalEntryDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordPurchaseReturn(purchaseReturnRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RawMaterialPurchaseControllerApi.recordPurchaseReturn']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RawMaterialPurchaseControllerApi - factory interface
 */
export const RawMaterialPurchaseControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RawMaterialPurchaseControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {RawMaterialPurchaseControllerApiCreatePurchaseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPurchase(requestParameters: RawMaterialPurchaseControllerApiCreatePurchaseRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialPurchaseResponse> {
            return localVarFp.createPurchase(requestParameters.rawMaterialPurchaseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialPurchaseControllerApiGetPurchaseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPurchase(requestParameters: RawMaterialPurchaseControllerApiGetPurchaseRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseRawMaterialPurchaseResponse> {
            return localVarFp.getPurchase(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPurchases(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListRawMaterialPurchaseResponse> {
            return localVarFp.listPurchases(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RawMaterialPurchaseControllerApiRecordPurchaseReturnRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordPurchaseReturn(requestParameters: RawMaterialPurchaseControllerApiRecordPurchaseReturnRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseJournalEntryDto> {
            return localVarFp.recordPurchaseReturn(requestParameters.purchaseReturnRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createPurchase operation in RawMaterialPurchaseControllerApi.
 */
export interface RawMaterialPurchaseControllerApiCreatePurchaseRequest {
    readonly rawMaterialPurchaseRequest: RawMaterialPurchaseRequest
}

/**
 * Request parameters for getPurchase operation in RawMaterialPurchaseControllerApi.
 */
export interface RawMaterialPurchaseControllerApiGetPurchaseRequest {
    readonly id: number
}

/**
 * Request parameters for recordPurchaseReturn operation in RawMaterialPurchaseControllerApi.
 */
export interface RawMaterialPurchaseControllerApiRecordPurchaseReturnRequest {
    readonly purchaseReturnRequest: PurchaseReturnRequest
}

/**
 * RawMaterialPurchaseControllerApi - object-oriented interface
 */
export class RawMaterialPurchaseControllerApi extends BaseAPI {
    /**
     * 
     * @param {RawMaterialPurchaseControllerApiCreatePurchaseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPurchase(requestParameters: RawMaterialPurchaseControllerApiCreatePurchaseRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialPurchaseControllerApiFp(this.configuration).createPurchase(requestParameters.rawMaterialPurchaseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialPurchaseControllerApiGetPurchaseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPurchase(requestParameters: RawMaterialPurchaseControllerApiGetPurchaseRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialPurchaseControllerApiFp(this.configuration).getPurchase(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPurchases(options?: RawAxiosRequestConfig) {
        return RawMaterialPurchaseControllerApiFp(this.configuration).listPurchases(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RawMaterialPurchaseControllerApiRecordPurchaseReturnRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recordPurchaseReturn(requestParameters: RawMaterialPurchaseControllerApiRecordPurchaseReturnRequest, options?: RawAxiosRequestConfig) {
        return RawMaterialPurchaseControllerApiFp(this.configuration).recordPurchaseReturn(requestParameters.purchaseReturnRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

