/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseCreditRequestDto } from '../models';
// @ts-ignore
import type { ApiResponseDispatchConfirmResponse } from '../models';
// @ts-ignore
import type { ApiResponseListCreditRequestDto } from '../models';
// @ts-ignore
import type { ApiResponseListPromotionDto } from '../models';
// @ts-ignore
import type { ApiResponseListSalesOrderDto } from '../models';
// @ts-ignore
import type { ApiResponseListSalesTargetDto } from '../models';
// @ts-ignore
import type { ApiResponsePromotionDto } from '../models';
// @ts-ignore
import type { ApiResponseSalesOrderDto } from '../models';
// @ts-ignore
import type { ApiResponseSalesTargetDto } from '../models';
// @ts-ignore
import type { CancelRequest } from '../models';
// @ts-ignore
import type { CreditRequestRequest } from '../models';
// @ts-ignore
import type { DispatchConfirmRequest } from '../models';
// @ts-ignore
import type { PromotionRequest } from '../models';
// @ts-ignore
import type { SalesOrderRequest } from '../models';
// @ts-ignore
import type { SalesTargetRequest } from '../models';
// @ts-ignore
import type { StatusRequest } from '../models';
/**
 * SalesControllerApi - axios parameter creator
 */
export const SalesControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {CancelRequest} [cancelRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrder: async (id: number, cancelRequest?: CancelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelOrder', 'id', id)
            const localVarPath = `/api/v1/sales/orders/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DispatchConfirmRequest} dispatchConfirmRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmDispatch: async (dispatchConfirmRequest: DispatchConfirmRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dispatchConfirmRequest' is not null or undefined
            assertParamExists('confirmDispatch', 'dispatchConfirmRequest', dispatchConfirmRequest)
            const localVarPath = `/api/v1/sales/dispatch/confirm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dispatchConfirmRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmOrder: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('confirmOrder', 'id', id)
            const localVarPath = `/api/v1/sales/orders/{id}/confirm`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreditRequestRequest} creditRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCreditRequest: async (creditRequestRequest: CreditRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'creditRequestRequest' is not null or undefined
            assertParamExists('createCreditRequest', 'creditRequestRequest', creditRequestRequest)
            const localVarPath = `/api/v1/sales/credit-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(creditRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SalesOrderRequest} salesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder: async (salesOrderRequest: SalesOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'salesOrderRequest' is not null or undefined
            assertParamExists('createOrder', 'salesOrderRequest', salesOrderRequest)
            const localVarPath = `/api/v1/sales/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(salesOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PromotionRequest} promotionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPromotion: async (promotionRequest: PromotionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'promotionRequest' is not null or undefined
            assertParamExists('createPromotion', 'promotionRequest', promotionRequest)
            const localVarPath = `/api/v1/sales/promotions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(promotionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SalesTargetRequest} salesTargetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTarget: async (salesTargetRequest: SalesTargetRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'salesTargetRequest' is not null or undefined
            assertParamExists('createTarget', 'salesTargetRequest', salesTargetRequest)
            const localVarPath = `/api/v1/sales/targets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(salesTargetRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creditRequests: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sales/credit-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOrder: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteOrder', 'id', id)
            const localVarPath = `/api/v1/sales/orders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromotion: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePromotion', 'id', id)
            const localVarPath = `/api/v1/sales/promotions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTarget: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTarget', 'id', id)
            const localVarPath = `/api/v1/sales/targets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orders: async (status?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sales/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        promotions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sales/promotions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        targets: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sales/targets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {CreditRequestRequest} creditRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCreditRequest: async (id: number, creditRequestRequest: CreditRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCreditRequest', 'id', id)
            // verify required parameter 'creditRequestRequest' is not null or undefined
            assertParamExists('updateCreditRequest', 'creditRequestRequest', creditRequestRequest)
            const localVarPath = `/api/v1/sales/credit-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(creditRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {SalesOrderRequest} salesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrder: async (id: number, salesOrderRequest: SalesOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateOrder', 'id', id)
            // verify required parameter 'salesOrderRequest' is not null or undefined
            assertParamExists('updateOrder', 'salesOrderRequest', salesOrderRequest)
            const localVarPath = `/api/v1/sales/orders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(salesOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {PromotionRequest} promotionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePromotion: async (id: number, promotionRequest: PromotionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePromotion', 'id', id)
            // verify required parameter 'promotionRequest' is not null or undefined
            assertParamExists('updatePromotion', 'promotionRequest', promotionRequest)
            const localVarPath = `/api/v1/sales/promotions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(promotionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus: async (id: number, statusRequest: StatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateStatus', 'id', id)
            // verify required parameter 'statusRequest' is not null or undefined
            assertParamExists('updateStatus', 'statusRequest', statusRequest)
            const localVarPath = `/api/v1/sales/orders/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(statusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {SalesTargetRequest} salesTargetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTarget: async (id: number, salesTargetRequest: SalesTargetRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTarget', 'id', id)
            // verify required parameter 'salesTargetRequest' is not null or undefined
            assertParamExists('updateTarget', 'salesTargetRequest', salesTargetRequest)
            const localVarPath = `/api/v1/sales/targets/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(salesTargetRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SalesControllerApi - functional programming interface
 */
export const SalesControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SalesControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {CancelRequest} [cancelRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelOrder(id: number, cancelRequest?: CancelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelOrder(id, cancelRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.cancelOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {DispatchConfirmRequest} dispatchConfirmRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirmDispatch(dispatchConfirmRequest: DispatchConfirmRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseDispatchConfirmResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirmDispatch(dispatchConfirmRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.confirmDispatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirmOrder(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirmOrder(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.confirmOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreditRequestRequest} creditRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCreditRequest(creditRequestRequest: CreditRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCreditRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCreditRequest(creditRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.createCreditRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SalesOrderRequest} salesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrder(salesOrderRequest: SalesOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrder(salesOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.createOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {PromotionRequest} promotionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPromotion(promotionRequest: PromotionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePromotionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPromotion(promotionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.createPromotion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SalesTargetRequest} salesTargetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTarget(salesTargetRequest: SalesTargetRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesTargetDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTarget(salesTargetRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.createTarget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async creditRequests(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListCreditRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.creditRequests(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.creditRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOrder(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOrder(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.deleteOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePromotion(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePromotion(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.deletePromotion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTarget(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTarget(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.deleteTarget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async orders(status?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.orders(status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.orders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async promotions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListPromotionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.promotions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.promotions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async targets(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListSalesTargetDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.targets(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.targets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {CreditRequestRequest} creditRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCreditRequest(id: number, creditRequestRequest: CreditRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCreditRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCreditRequest(id, creditRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.updateCreditRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {SalesOrderRequest} salesOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOrder(id: number, salesOrderRequest: SalesOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOrder(id, salesOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.updateOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {PromotionRequest} promotionRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePromotion(id: number, promotionRequest: PromotionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePromotionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePromotion(id, promotionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.updatePromotion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {StatusRequest} statusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateStatus(id: number, statusRequest: StatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesOrderDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateStatus(id, statusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.updateStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {SalesTargetRequest} salesTargetRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTarget(id: number, salesTargetRequest: SalesTargetRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSalesTargetDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTarget(id, salesTargetRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SalesControllerApi.updateTarget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SalesControllerApi - factory interface
 */
export const SalesControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SalesControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {SalesControllerApiCancelOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelOrder(requestParameters: SalesControllerApiCancelOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesOrderDto> {
            return localVarFp.cancelOrder(requestParameters.id, requestParameters.cancelRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiConfirmDispatchRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmDispatch(requestParameters: SalesControllerApiConfirmDispatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseDispatchConfirmResponse> {
            return localVarFp.confirmDispatch(requestParameters.dispatchConfirmRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiConfirmOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmOrder(requestParameters: SalesControllerApiConfirmOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesOrderDto> {
            return localVarFp.confirmOrder(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiCreateCreditRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCreditRequest(requestParameters: SalesControllerApiCreateCreditRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCreditRequestDto> {
            return localVarFp.createCreditRequest(requestParameters.creditRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiCreateOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder(requestParameters: SalesControllerApiCreateOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesOrderDto> {
            return localVarFp.createOrder(requestParameters.salesOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiCreatePromotionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPromotion(requestParameters: SalesControllerApiCreatePromotionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePromotionDto> {
            return localVarFp.createPromotion(requestParameters.promotionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiCreateTargetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTarget(requestParameters: SalesControllerApiCreateTargetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesTargetDto> {
            return localVarFp.createTarget(requestParameters.salesTargetRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        creditRequests(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListCreditRequestDto> {
            return localVarFp.creditRequests(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiDeleteOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOrder(requestParameters: SalesControllerApiDeleteOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteOrder(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiDeletePromotionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePromotion(requestParameters: SalesControllerApiDeletePromotionRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePromotion(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiDeleteTargetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteTarget(requestParameters: SalesControllerApiDeleteTargetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTarget(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiOrdersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        orders(requestParameters: SalesControllerApiOrdersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListSalesOrderDto> {
            return localVarFp.orders(requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        promotions(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListPromotionDto> {
            return localVarFp.promotions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        targets(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListSalesTargetDto> {
            return localVarFp.targets(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiUpdateCreditRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCreditRequest(requestParameters: SalesControllerApiUpdateCreditRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCreditRequestDto> {
            return localVarFp.updateCreditRequest(requestParameters.id, requestParameters.creditRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiUpdateOrderRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrder(requestParameters: SalesControllerApiUpdateOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesOrderDto> {
            return localVarFp.updateOrder(requestParameters.id, requestParameters.salesOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiUpdatePromotionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePromotion(requestParameters: SalesControllerApiUpdatePromotionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePromotionDto> {
            return localVarFp.updatePromotion(requestParameters.id, requestParameters.promotionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiUpdateStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateStatus(requestParameters: SalesControllerApiUpdateStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesOrderDto> {
            return localVarFp.updateStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SalesControllerApiUpdateTargetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTarget(requestParameters: SalesControllerApiUpdateTargetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSalesTargetDto> {
            return localVarFp.updateTarget(requestParameters.id, requestParameters.salesTargetRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cancelOrder operation in SalesControllerApi.
 */
export interface SalesControllerApiCancelOrderRequest {
    readonly id: number

    readonly cancelRequest?: CancelRequest
}

/**
 * Request parameters for confirmDispatch operation in SalesControllerApi.
 */
export interface SalesControllerApiConfirmDispatchRequest {
    readonly dispatchConfirmRequest: DispatchConfirmRequest
}

/**
 * Request parameters for confirmOrder operation in SalesControllerApi.
 */
export interface SalesControllerApiConfirmOrderRequest {
    readonly id: number
}

/**
 * Request parameters for createCreditRequest operation in SalesControllerApi.
 */
export interface SalesControllerApiCreateCreditRequestRequest {
    readonly creditRequestRequest: CreditRequestRequest
}

/**
 * Request parameters for createOrder operation in SalesControllerApi.
 */
export interface SalesControllerApiCreateOrderRequest {
    readonly salesOrderRequest: SalesOrderRequest
}

/**
 * Request parameters for createPromotion operation in SalesControllerApi.
 */
export interface SalesControllerApiCreatePromotionRequest {
    readonly promotionRequest: PromotionRequest
}

/**
 * Request parameters for createTarget operation in SalesControllerApi.
 */
export interface SalesControllerApiCreateTargetRequest {
    readonly salesTargetRequest: SalesTargetRequest
}

/**
 * Request parameters for deleteOrder operation in SalesControllerApi.
 */
export interface SalesControllerApiDeleteOrderRequest {
    readonly id: number
}

/**
 * Request parameters for deletePromotion operation in SalesControllerApi.
 */
export interface SalesControllerApiDeletePromotionRequest {
    readonly id: number
}

/**
 * Request parameters for deleteTarget operation in SalesControllerApi.
 */
export interface SalesControllerApiDeleteTargetRequest {
    readonly id: number
}

/**
 * Request parameters for orders operation in SalesControllerApi.
 */
export interface SalesControllerApiOrdersRequest {
    readonly status?: string
}

/**
 * Request parameters for updateCreditRequest operation in SalesControllerApi.
 */
export interface SalesControllerApiUpdateCreditRequestRequest {
    readonly id: number

    readonly creditRequestRequest: CreditRequestRequest
}

/**
 * Request parameters for updateOrder operation in SalesControllerApi.
 */
export interface SalesControllerApiUpdateOrderRequest {
    readonly id: number

    readonly salesOrderRequest: SalesOrderRequest
}

/**
 * Request parameters for updatePromotion operation in SalesControllerApi.
 */
export interface SalesControllerApiUpdatePromotionRequest {
    readonly id: number

    readonly promotionRequest: PromotionRequest
}

/**
 * Request parameters for updateStatus operation in SalesControllerApi.
 */
export interface SalesControllerApiUpdateStatusRequest {
    readonly id: number

    readonly statusRequest: StatusRequest
}

/**
 * Request parameters for updateTarget operation in SalesControllerApi.
 */
export interface SalesControllerApiUpdateTargetRequest {
    readonly id: number

    readonly salesTargetRequest: SalesTargetRequest
}

/**
 * SalesControllerApi - object-oriented interface
 */
export class SalesControllerApi extends BaseAPI {
    /**
     * 
     * @param {SalesControllerApiCancelOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelOrder(requestParameters: SalesControllerApiCancelOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).cancelOrder(requestParameters.id, requestParameters.cancelRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiConfirmDispatchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public confirmDispatch(requestParameters: SalesControllerApiConfirmDispatchRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).confirmDispatch(requestParameters.dispatchConfirmRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiConfirmOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public confirmOrder(requestParameters: SalesControllerApiConfirmOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).confirmOrder(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiCreateCreditRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createCreditRequest(requestParameters: SalesControllerApiCreateCreditRequestRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).createCreditRequest(requestParameters.creditRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiCreateOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrder(requestParameters: SalesControllerApiCreateOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).createOrder(requestParameters.salesOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiCreatePromotionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPromotion(requestParameters: SalesControllerApiCreatePromotionRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).createPromotion(requestParameters.promotionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiCreateTargetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTarget(requestParameters: SalesControllerApiCreateTargetRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).createTarget(requestParameters.salesTargetRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public creditRequests(options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).creditRequests(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiDeleteOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteOrder(requestParameters: SalesControllerApiDeleteOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).deleteOrder(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiDeletePromotionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePromotion(requestParameters: SalesControllerApiDeletePromotionRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).deletePromotion(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiDeleteTargetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteTarget(requestParameters: SalesControllerApiDeleteTargetRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).deleteTarget(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiOrdersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public orders(requestParameters: SalesControllerApiOrdersRequest = {}, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).orders(requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public promotions(options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).promotions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public targets(options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).targets(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiUpdateCreditRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateCreditRequest(requestParameters: SalesControllerApiUpdateCreditRequestRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).updateCreditRequest(requestParameters.id, requestParameters.creditRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiUpdateOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateOrder(requestParameters: SalesControllerApiUpdateOrderRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).updateOrder(requestParameters.id, requestParameters.salesOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiUpdatePromotionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePromotion(requestParameters: SalesControllerApiUpdatePromotionRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).updatePromotion(requestParameters.id, requestParameters.promotionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiUpdateStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateStatus(requestParameters: SalesControllerApiUpdateStatusRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).updateStatus(requestParameters.id, requestParameters.statusRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SalesControllerApiUpdateTargetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTarget(requestParameters: SalesControllerApiUpdateTargetRequest, options?: RawAxiosRequestConfig) {
        return SalesControllerApiFp(this.configuration).updateTarget(requestParameters.id, requestParameters.salesTargetRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

