/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AgingBucketDto } from './aging-bucket-dto';

export interface AgingSummaryResponse {
    'partnerId'?: number;
    'partnerName'?: string;
    'totalOutstanding'?: number;
    'buckets'?: Array<AgingBucketDto>;
}

