/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceDto } from './invoice-dto';

export interface ApiResponseListInvoiceDto {
    'success'?: boolean;
    'message'?: string;
    'data'?: Array<InvoiceDto>;
    'timestamp'?: string;
}

