/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BankReconciliationRequest {
    'bankAccountId': number;
    'statementDate': string;
    'statementEndingBalance': number;
    'startDate'?: string;
    'endDate'?: string;
    'clearedReferences'?: Array<string>;
    'accountingPeriodId'?: number;
    'markAsComplete'?: boolean;
    'note'?: string;
}

