/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImportError } from './import-error';

export interface CatalogImportResponse {
    'rowsProcessed'?: number;
    'brandsCreated'?: number;
    'productsCreated'?: number;
    'productsUpdated'?: number;
    'rawMaterialsSeeded'?: number;
    'errors'?: Array<ImportError>;
}

