/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CostBreakdownDto {
    'productionLogId'?: number;
    'productionCode'?: string;
    'productName'?: string;
    'batchColour'?: string;
    'mixedQuantity'?: number;
    'materialCostTotal'?: number;
    'laborCostTotal'?: number;
    'overheadCostTotal'?: number;
    'totalCost'?: number;
    'unitCost'?: number;
    'producedAt'?: string;
}

