/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SettlementAllocationRequest } from './settlement-allocation-request';

export interface DealerSettlementRequest {
    'dealerId': number;
    'cashAccountId': number;
    'discountAccountId'?: number;
    'writeOffAccountId'?: number;
    'fxGainAccountId'?: number;
    'fxLossAccountId'?: number;
    'settlementDate'?: string;
    'referenceNumber'?: string;
    'memo'?: string;
    'idempotencyKey'?: string;
    'adminOverride'?: boolean;
    'allocations': Array<SettlementAllocationRequest>;
}

