/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface InventoryCountResponse {
    'itemId'?: number;
    'itemName'?: string;
    'target'?: InventoryCountResponseTargetEnum;
    'systemQuantity'?: number;
    'physicalQuantity'?: number;
    'varianceQuantity'?: number;
    'varianceValue'?: number;
    'adjustmentPosted'?: boolean;
    'journalEntryId'?: number;
    'alertRaised'?: boolean;
    'alertReason'?: string;
}

export const InventoryCountResponseTargetEnum = {
    RawMaterial: 'RAW_MATERIAL',
    FinishedGood: 'FINISHED_GOOD'
} as const;

export type InventoryCountResponseTargetEnum = typeof InventoryCountResponseTargetEnum[keyof typeof InventoryCountResponseTargetEnum];


