/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceLineDto } from './invoice-line-dto';

export interface InvoiceDto {
    'id'?: number;
    'publicId'?: string;
    'invoiceNumber'?: string;
    'status'?: string;
    'subtotal'?: number;
    'taxTotal'?: number;
    'totalAmount'?: number;
    'outstandingAmount'?: number;
    'currency'?: string;
    'issueDate'?: string;
    'dueDate'?: string;
    'dealerId'?: number;
    'dealerName'?: string;
    'salesOrderId'?: number;
    'journalEntryId'?: number;
    'createdAt'?: string;
    'lines'?: Array<InvoiceLineDto>;
}

