/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JournalLineDto } from './journal-line-dto';

export interface JournalEntryDto {
    'id'?: number;
    'publicId'?: string;
    'referenceNumber'?: string;
    'entryDate'?: string;
    'memo'?: string;
    'status'?: string;
    'dealerId'?: number;
    'dealerName'?: string;
    'supplierId'?: number;
    'supplierName'?: string;
    'accountingPeriodId'?: number;
    'accountingPeriodLabel'?: string;
    'accountingPeriodStatus'?: string;
    'reversalOfEntryId'?: number;
    'reversalEntryId'?: number;
    'correctionType'?: string;
    'correctionReason'?: string;
    'voidReason'?: string;
    'lines'?: Array<JournalLineDto>;
    'createdAt'?: string;
    'updatedAt'?: string;
    'postedAt'?: string;
    'createdBy'?: string;
    'postedBy'?: string;
    'lastModifiedBy'?: string;
}

