/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JournalLineRequest } from './journal-line-request';

export interface JournalEntryRequest {
    'referenceNumber'?: string;
    'entryDate': string;
    'memo'?: string;
    'dealerId'?: number;
    'supplierId'?: number;
    'adminOverride'?: boolean;
    'lines': Array<JournalLineRequest>;
    'currency'?: string;
    'fxRate'?: number;
}

