/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountingPeriodDto } from './accounting-period-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MonthEndChecklistItemDto } from './month-end-checklist-item-dto';

export interface MonthEndChecklistDto {
    'period'?: AccountingPeriodDto;
    'items'?: Array<MonthEndChecklistItemDto>;
    'readyToClose'?: boolean;
}

