/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MonthlyProductionCostDto {
    'year'?: number;
    'month'?: number;
    'batchCount'?: number;
    'totalLitersProduced'?: number;
    'totalMaterialCost'?: number;
    'totalLaborCost'?: number;
    'totalOverheadCost'?: number;
    'totalCost'?: number;
    'avgCostPerLiter'?: number;
    'totalWastageQuantity'?: number;
    'wastagePercentage'?: number;
}

