/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PackingRecordDto {
    'id'?: number;
    'packagingSize'?: string;
    'quantityPacked'?: number;
    'piecesCount'?: number;
    'boxesCount'?: number;
    'piecesPerBox'?: number;
    'packedDate'?: string;
    'packedBy'?: string;
}

