/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PayrollRunRequest {
    'payrollDate': string;
    'initiatedBy': string;
    'debitAccountId': number;
    'creditAccountId': number;
    'postingAmount': number;
}

