/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductionLogMaterialDto } from './production-log-material-dto';

export interface ProductionLogDetailDto {
    'id'?: number;
    'publicId'?: string;
    'productionCode'?: string;
    'producedAt'?: string;
    'brandName'?: string;
    'productName'?: string;
    'skuCode'?: string;
    'batchColour'?: string;
    'batchSize'?: number;
    'unitOfMeasure'?: string;
    'mixedQuantity'?: number;
    'totalPackedQuantity'?: number;
    'wastageQuantity'?: number;
    'status'?: string;
    'materialCostTotal'?: number;
    'laborCostTotal'?: number;
    'overheadCostTotal'?: number;
    'unitCost'?: number;
    'salesOrderId'?: number;
    'salesOrderNumber'?: string;
    'notes'?: string;
    'createdBy'?: string;
    'materials'?: Array<ProductionLogMaterialDto>;
}

