/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProductCreateRequest {
    'brandId'?: number;
    'brandName'?: string;
    'brandCode'?: string;
    'productName': string;
    'category': string;
    'defaultColour'?: string;
    'sizeLabel'?: string;
    'unitOfMeasure'?: string;
    'customSkuCode'?: string;
    'basePrice'?: number;
    'gstRate'?: number;
    'minDiscountPercent'?: number;
    'minSellingPrice'?: number;
    'metadata'?: { [key: string]: object; };
}

