/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RawMaterialDto {
    'id'?: number;
    'publicId'?: string;
    'name'?: string;
    'sku'?: string;
    'unitType'?: string;
    'reorderLevel'?: number;
    'currentStock'?: number;
    'minStock'?: number;
    'maxStock'?: number;
    'stockStatus'?: string;
    'inventoryAccountId'?: number;
}

