/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RawMaterialPurchaseLineResponse {
    'rawMaterialId'?: number;
    'rawMaterialName'?: string;
    'rawMaterialBatchId'?: number;
    'batchCode'?: string;
    'quantity'?: number;
    'unit'?: string;
    'costPerUnit'?: number;
    'lineTotal'?: number;
    'notes'?: string;
}

