/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Row {
    'accountId'?: number;
    'code'?: string;
    'name'?: string;
    'type'?: RowTypeEnum;
    'debit'?: number;
    'credit'?: number;
}

export const RowTypeEnum = {
    Asset: 'ASSET',
    Liability: 'LIABILITY',
    Equity: 'EQUITY',
    Revenue: 'REVENUE',
    Expense: 'EXPENSE',
    Cogs: 'COGS'
} as const;

export type RowTypeEnum = typeof RowTypeEnum[keyof typeof RowTypeEnum];


