/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SalesOrderItemRequest } from './sales-order-item-request';

export interface SalesOrderRequest {
    'dealerId'?: number;
    'totalAmount': number;
    'currency'?: string;
    'notes'?: string;
    'items': Array<SalesOrderItemRequest>;
    'gstTreatment'?: string;
    'gstRate'?: number;
    'gstInclusive'?: boolean;
    'idempotencyKey'?: string;
}

