/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SalesOrderItemDto } from './sales-order-item-dto';

export interface SalesOrderDto {
    'id'?: number;
    'publicId'?: string;
    'orderNumber'?: string;
    'status'?: string;
    'totalAmount'?: number;
    'subtotalAmount'?: number;
    'gstTotal'?: number;
    'gstRate'?: number;
    'gstTreatment'?: string;
    'gstRoundingAdjustment'?: number;
    'currency'?: string;
    'dealerName'?: string;
    'traceId'?: string;
    'createdAt'?: string;
    'items'?: Array<SalesOrderItemDto>;
}

