/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SupplierResponse {
    'id'?: number;
    'publicId'?: string;
    'code'?: string;
    'name'?: string;
    'status'?: string;
    'email'?: string;
    'phone'?: string;
    'address'?: string;
    'creditLimit'?: number;
    'outstandingBalance'?: number;
    'payableAccountId'?: number;
    'payableAccountCode'?: string;
}

