/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserDto {
    'id'?: number;
    'publicId'?: string;
    'email'?: string;
    'displayName'?: string;
    'enabled'?: boolean;
    'mfaEnabled'?: boolean;
    'roles'?: Array<string>;
    'companies'?: Array<string>;
}

