/* tslint:disable */
/* eslint-disable */
/**
 * BigBright ERP Domain API
 * Core APIs for multi-company ERP platform
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WastageReportDto {
    'productionLogId'?: number;
    'productionCode'?: string;
    'productName'?: string;
    'batchColour'?: string;
    'mixedQuantity'?: number;
    'totalPackedQuantity'?: number;
    'wastageQuantity'?: number;
    'wastagePercentage'?: number;
    'wastageValue'?: number;
    'producedAt'?: string;
}

